# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20160908_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
