# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 22:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_auto_20161102_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorites_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
