# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import loginsys.models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0002_auto_20170310_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='images/default_profile_pic.jpg', upload_to=loginsys.models.UserProfile.get_file_path),
        ),
    ]
